New Web Application
theskinnerbox/ASTEF pull request #7
Opened 2016-06-11 10:01 UTC by francescomalatesta

Here's the new version of the ASTEF web application.

You will find the instructions to use it in the `src/webapp/README.md` file.

For my tests, I actually I used the [flightdeck-fix.txt](https://github.com/theskinnerbox/ASTEF/blob/master/demo_data/flightdeck-fix.txt) file. 

The only thing that remains left to implement is the background image upload for the chart, but I am experiencing some issues with it. I will update you ASAP.

Have a nice weekend! :)

EDIT: don't merge it right now, let's test it first with other fixations txt files.

EDIT2: live demo @ [http://astef-web.netlify.com/](http://astef-web.netlify.com/) (it's a cheap free hosting, so it could take a while to load :D)

2016-06-24 15:23 UTC, wbigger commented
Well done! Some notes:
- start the minute counting from 1 instead of zero
- add a "Save time series" button that save the file as in the matlab version:
[flightdeck-fix-nni.txt](https://github.com/theskinnerbox/ASTEF/files/331979/flightdeck-fix-nni.txt)

2016-06-25 08:12 UTC, francescomalatesta commented
More notes from @dinocera :

* change the color of the current NNI value;
* upload a background picture for the scanpath;
* instead of "Per Minute Fixations", use "Scanpath";

2016-07-04 20:52 UTC, francescomalatesta commented
Currently done:

- start the minute counting from one instead of zero
- add a "Save time series" button that saves a file with NNI values as in the matlab version: flightdeck-fix-nni.txt
- instead of "Per Minute Fixations", use "Scanpath";

The remaining ones,

- change the color of the current NNI value;
- upload a background picture for the scanpath;

seems to be a problem for our charts library. I'll let you know if I can figure out something :)

2017-01-05 15:30 UTC, wbigger requested changes
Ciao Francesco, ho fatto dei test e c'è una modifica da fare sulla suddivisione delle fissazioni per minuto.

2017-01-05 15:30 UTC, wbigger commented on src/webapp/src/Processors/FixationsDataProcessor.js
> +        let minute = Math.floor(timestamp * 1.67 * 0.00001);
Questa formula è approssimata e porta a risultati diversi da quelli di matlab! Usare una formula più precisa, ad esempio
`let minute = Math.floor(timestamp / 1000 / 60);`

2017-01-22 10:34 UTC, francescomalatesta commented on src/webapp/src/Processors/FixationsDataProcessor.js
> +        let minute = Math.floor(timestamp * 1.67 * 0.00001);
Sistemato!

2017-01-23 09:38 UTC, wbigger approved these changes

2017-01-23 10:04 UTC, wbigger commented
Issues:
- [x] change the color of the current NNI value
- [ ] upload a background picture for the scanpath;

The image is correctly loaded but not properly resized. The whole image should be resized to fit the drawing area. Indeed, the fixations has to exactly overlay the background image.

Correct example, from Matlab implementation:
<img width="1129" alt="screen shot 2017-01-23 at 10 37 10 am" src="https://cloud.githubusercontent.com/assets/3594326/22198853/a3e31898-e158-11e6-9aa6-7d439b57d440.png">

Current implementation in my browser (Chrome 55.0.2883.95 on macOS Sierra):
![screen shot 2017-01-23 at 10 36 59 am](https://cloud.githubusercontent.com/assets/3594326/22198852/a3e2b7d6-e158-11e6-84d3-599e8ea91db7.png)

2017-01-23 18:29 UTC, francescomalatesta commented
@wbigger this seems very strange, actually I am using Chrome 52 on Ubuntu and I am not experiencing any issues. However, try again now, it should be fixed as I fixed the resize event. Tomorrow I will also try it at office.

2017-01-24 16:37 UTC, wbigger commented
@francescomalatesta still the same issue with the last version :(

2017-01-24 17:53 UTC, francescomalatesta commented
@wbigger so strange :( will try tomorrow with a friend's Mac, will keep you updated!

2017-01-30 09:39 UTC, wbigger approved these changes
Still to fix a resize in background. Approving to split this repo into several repo, each one language-specific. The next changes will be made with more atomic fixes!

2017-01-30 18:28 UTC, merged